general:
  project_name: Przejazdowka
  model_type: st_yolo_x
#choices=[st_ssd_mobilenet_v1, ssd_mobilenet_v2_fpnlite, tiny_yolo_v2, st_yolo_lc_v1, 
#         st_yolo_x, yolo_v8, yolo_v5u]
  #model_path: C:\Users\alert\repos\stm32ai-modelzoo\object_detection\st_yolo_x\ST_pretrainedmodel_public_dataset\coco_2017_80_classes\st_yolo_x_nano_480\st_yolo_x_nano_480_1.0_0.25_3.h5
  logs_dir: logs
  saved_models_dir: ../../experiments_outputs/saved_models
  display_figures: True
  gpu_memory_limit: 16
  num_threads_tflite: 4
  global_seed: 127

operation_mode: chain_tqeb
#choices=['training' , 'evaluation', 'deployment', 'quantization', 'benchmarking',
#        'chain_tqeb','chain_tqe','chain_eqe','chain_qb','chain_eqeb','chain_qd ']

dataset:
   name: Cars_dataset    
   class_names: [ car ]
   training_path: ../datasets/Cars_dataset/train/
   validation_path: ../datasets/Cars_dataset/valid/
   validation_split: 
   test_path: ../datasets/Cars_dataset/test/
   quantization_path: ../datasets/Cars_dataset/train/
   quantization_split:

preprocessing:
  rescaling: { scale: 1/255, offset: 0 }
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb
       
# data_augmentation:
#   random_contrast:
#     factor: 0.4
#   random_brightness:
#     factor: 0.3
#   random_flip:
#     mode: horizontal
#   random_translation:
#     width_factor: 0.1
#     height_factor: 0.1
#   random_rotation:
#     factor: 0.05

training:
  model:
    input_shape: (480, 480, 3)
    depth_mul: 1.0
    width_mul: 1.0
    #pretrained_weights: imagenet
  dropout: null
  batch_size: 2
  epochs: 12
  optimizer:
    Adam:
      learning_rate: 0.0025
  callbacks:
    ReduceLROnPlateau:
      monitor: val_map
      patience: 10
      factor: 0.25
    ModelCheckpoint:
      monitor: val_map
    EarlyStopping:
      monitor: val_loss
      patience: 10
      restore_best_weights: True
      verbose: 1

postprocessing:
  yolo_anchors: [0.5, 0.5, 0.07, 0.25, 0.23, 0.7]  
  confidence_thresh: 0.01
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.4
  plot_metrics: True
  max_detection_boxes: 100

quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models


tools:
  stedgeai:
    version: 10.0.0
    optimization: balanced
    on_cloud: False
    path_to_stedgeai: C:/Users/alert/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/10.0.0/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.14.1/STM32CubeIDE/stm32cubeide.exe

benchmarking:
  board: STM32N6570-DK

# deployment:
#   c_project_path: ../../application_code/object_detection/STM32H7/
#   IDE: GCC
#   verbosity: 1
#   hardware_setup:
#     serie: STM32H7
#     board: STM32H747I-DISCO

mlflow:
  uri: ../../experiments_outputs/mlruns

hydra:
  run:
    dir: ../../experiments_outputs/output #${now:%Y_%m_%d_%H_%M_%S}
    