dataset:
  dataset_name: Furniture
  training_path: ../Furniture/train
  validation_path: ../Furniture/valid
  test_path: ../Furniture/test

settings:
  max_detections: 20
  
hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}
