dataset:
  dataset_name: Cars_dataset
  training_path: ../Cars_dataset/train
  validation_path: ../Cars_dataset/valid
  test_path: ../Cars_dataset/test

settings:
  max_detections: 20
  
hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}
