general:
   model_path: ../../experiments_outputs/output/quantized_models/quantized_model.tflite # C:\Users\alert\repos\stm32ai-modelzoo\object_detection\st_yolo_x\ST_pretrainedmodel_public_dataset\coco_2017_person\st_yolo_x_nano_480/st_yolo_x_nano_480_1.0_0.25_3_int8.tflite # ../../experiments_outputs/output/quantized_models/quantized_model.tflite
   model_type: st_yolo_x
   display_figures: True
operation_mode: deployment

dataset:
   name: Cars_dataset
   #class_names: ['person']
   class_names: [car]

preprocessing:
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb

postprocessing:
  yolo_anchors: [0.5, 0.5, 0.07, 0.25, 0.23, 0.7]
  confidence_thresh: 0.01
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: false
  max_detection_boxes: 10

tools:
  stedgeai:
    version: 10.0.0
    optimization: balanced
    on_cloud: False
    path_to_stedgeai: C:/ST/STEdgeAI/2.1/Utilities/windows/stedgeai.exe # C:/Users/alert/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/10.0.0/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.14.1/STM32CubeIDE/stm32cubeide.exe

deployment:
  c_project_path: ../../application_code/object_detection/STM32N6/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32N6
    board: STM32N6570-DK

mlflow:
   uri: ../../experiments_outputs/mlruns

hydra:
   run:
      dir: ../../experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}