general:
   model_path: ../../experiments_outputs/output/quantized_models/quantized_model.tflite
   model_type: st_yolo_x
   display_figures: True
operation_mode: deployment

dataset:
   name: Cars_dataset
   class_names: [car]

preprocessing:
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb

postprocessing:
  confidence_thresh: 0.6
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.3
  max_detection_boxes: 10

tools:
  stedgeai:
    version: 10.0.0
    optimization: balanced
    on_cloud: False
    path_to_stedgeai: C:/ST/STEdgeAI/2.1/Utilities/windows/stedgeai.exe # C:/Users/alert/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/10.0.0/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.14.1/STM32CubeIDE/stm32cubeide.exe

deployment:
  c_project_path: ../../application_code/object_detection/STM32N6/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32N6
    board: STM32N6570-DK

mlflow:
   uri: ../../experiments_outputs/mlruns

hydra:
   run:
      dir: ../../experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}